# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-12 19:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('potato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likedone',
            field=models.ManyToManyField(related_name='users_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='thumbnumber',
            field=models.IntegerField(default=0, help_text='Начинается с 0', verbose_name='Число лайков'),
        ),
        migrations.AddField(
            model_name='post',
            name='likedone',
            field=models.ManyToManyField(related_name='users_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnumber',
            field=models.IntegerField(default=0, help_text='Начинается с 0', verbose_name='Число лайков'),
        ),
    ]
