# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-21 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potato', '0002_auto_20190516_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='potato.Event', verbose_name='Пост'),
        ),
        migrations.AddField(
            model_name='event',
            name='maxparticipant',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальное число участников'),
        ),
        migrations.AddField(
            model_name='event',
            name='minparticipant',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальное число участников'),
        ),
        migrations.AddField(
            model_name='event',
            name='thumbnumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='Число участников'),
        ),
        migrations.AlterField(
            model_name='event',
            name='age_limit',
            field=models.IntegerField(choices=[(12, 12), (16, 16), (18, 18)], verbose_name='Возрастное ограничение'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('S', 'Sport'), ('H', 'Hobby'), ('P', 'Party'), ('O', 'Other')], max_length=30, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='event',
            name='data_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='event',
            name='data_when',
            field=models.DateField(blank=True, null=True, verbose_name='Дата проведения'),
        ),
    ]
